services:
  gitlab:
    image: gitlab/gitlab-ce
    pull_policy: always
    container_name: gitlab
    restart: always
    hostname: 'docker-gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['initial_root_password'] = '${initial_root_password}'
    ports:
      - '80:80'
      - '443:443'
      - '2424:22'
    volumes:
      - "${gitlab_config}:/etc/gitlab"
      - "${gitlab_logs}:/var/log/gitlab"
      - "${gitlab_data}:/var/opt/gitlab"
    shm_size: '256m'
